const INGREDIENT_STATIC_VERSION = 3

function ingredientStaticUrl(filename) {
	return `/static/ingredients/${filename}?v=${INGREDIENT_STATIC_VERSION}`
}

const NAME_TO_FILE = {
	苹果: 'apple.png',
	香蕉: 'banana.png',
	牛肉: 'beef.png',
	西兰花: 'broccoli.png',
	花椰菜: 'broccoli.png',
	胡萝卜: 'carrot.png',
	鸡胸肉: 'chicken_breast.png',
	鸡肉: 'chicken_breast.png',
	黄瓜: 'cucumber.png',
	鸡蛋: 'egg.png',
	生菜: 'lettuce.png',
	牛奶: 'milk.png',
	蘑菇: 'mushroom.png',
	香菇: 'mushroom.png',
	面条: 'noodle..png',
	洋葱: 'onion.png',
	橙子: 'orange.png',
	猪肉: 'pork.png',
	土豆: 'potato.png',
	马铃薯: 'potato.png',
	大米: 'rice.png',
	米饭: 'rice.png',
	虾: 'shrimp.png',
	豆腐: 'tofu.png',
	番茄: 'tomato.png',
	西红柿: 'tomato.png'
}

const CATEGORY_TO_FILE = {
	水果: 'apple.png',
	蔬菜: 'broccoli.png',
	肉类: 'beef.png',
	蛋奶: 'egg.png',
	海鲜: 'shrimp.png',
	饮料: 'milk.png',
	调味品: 'onion.png',
	其他: 'tomato.png'
}

const CATEGORY_TO_EMOJI = {
	水果: '🍎',
	蔬菜: '🥬',
	肉类: '🥩',
	蛋奶: '🥚',
	海鲜: '🦐',
	饮料: '🥛',
	调味品: '🧂',
	其他: '🍽️'
}

const NAME_TO_ICONFONT = {
	苹果: 'icon-pingguo',
	香蕉: 'icon-xiangjiao',
	牛肉: 'icon-niurou',
	西兰花: 'icon-xilanhua',
	熟西兰花: 'icon-shuxilanhua',
	菠菜: 'icon-bocai',
	生菜: 'icon-shengcai',
	卷心菜: 'icon-juanxincai',
	白菜: 'icon-baicai',
	小白菜: 'icon-xiaobaicai',
	菜心: 'icon-caixin',
	青菜: 'icon-qingcai',
	上海青: 'icon-shanghaiqing',
	娃娃菜: 'icon-wawacai',
	花菜: 'icon-huacai',
	南瓜: 'icon-nangua',
	贝贝南瓜: 'icon-beibeinangua',
	黄瓜: 'icon-huanggua',
	青椒: 'icon-qingjiao',
	冬瓜: 'icon-donggua',
	豆芽: 'icon-douya',
	豌豆: 'icon-wandou',
	毛豆: 'icon-maodou',
	黄豆: 'icon-huangdou',
	黑豆: 'icon-heidou',
	红豆: 'icon-hongdou',
	白萝卜: 'icon-bailuobu',
	胡萝卜: 'icon-huluobu',
	红萝卜: 'icon-huluobu',
	生胡萝卜: 'icon-shenghuluobu',
	萝卜: 'icon-luobu',
	番茄: 'icon-fanqie',
	西红柿: 'icon-fanqie',
	小番茄: 'icon-xiaofanqie',
	圣女果: 'icon-shengnvguo',
	茄子: 'icon-xiaofanqie',
	紫茄子: 'icon-xiaofanqie',
	长茄子: 'icon-xiaofanqie',
	土豆: 'icon-tudou',
	马铃薯: 'icon-tudou',
	山药: 'icon-shanyao',
	玉米: 'icon-xianyumi',
	鲜玉米: 'icon-xianyumi',
	黄玉米: 'icon-huangyumi',
	白玉米: 'icon-baiyumi',
	大米: 'icon-mifan',
	米饭: 'icon-mifan',
	鸡蛋: 'icon-jidan',
	鸡蛋白: 'icon-jidanbai',
	卤蛋: 'icon-ludan',
	煎蛋: 'icon-jiandan',
	煮鸡蛋: 'icon-zhujidan',
	茶叶蛋: 'icon-chayedan',
	牛奶: 'icon-niunai',
	全脂牛奶: 'icon-quanzhiniunai',
	脱脂牛奶: 'icon-tuozhiniunai',
	伊利纯牛奶: 'icon-yilichunniunai',
	酸奶: 'icon-suannai',
	无糖酸奶: 'icon-wutangsuannai',
	奶酪: 'icon-nailao',
	豆腐: 'icon-doufu',
	内脂豆腐: 'icon-neizhidoufu',
	内酯豆腐: 'icon-neizhidoufu',
	油豆腐: 'icon-youdoufu',
	豆皮: 'icon-doupi',
	腐竹: 'icon-fuzhu',
	千张: 'icon-qianzhang',
	蘑菇: 'icon-mogu',
	香菇: 'icon-mogu',
	金针菇: 'icon-jinzhengu',
	牛排: 'icon-niupai',
	猪肉: 'icon-zhurou',
	'猪肉(肥瘦)': 'icon-a-zhuroufeisou',
	鸡肉: 'icon-jirou',
	鸡胸肉: 'icon-jixiongrou',
	烤鸡翅: 'icon-kaojichi',
	排骨: 'icon-paigu',
	培根: 'icon-peigen',
	火腿: 'icon-huotui',
	火腿肠: 'icon-huotuichang',
	香肠: 'icon-xiangchang',
	炸鸡腿: 'icon-zhajitui',
	虾: 'icon-xia',
	虾仁: 'icon-xiaren',
	鸡尾虾: 'icon-jiweixia',
	生三文鱼: 'icon-shengsanwenyu',
	'鲑鱼(三文鱼)': 'icon-a-guiyusanwenyu',
	鲑鱼: 'icon-a-guiyusanwenyu',
	三文鱼: 'icon-a-guiyusanwenyu',
	面条: 'icon-miantiao',
	煮面条: 'icon-zhumiantiao',
	方便面: 'icon-fangbianmian',
	花卷: 'icon-huajuan',
	吐司: 'icon-tusi',
	全麦面包: 'icon-quanmaimianbao',
	豆浆: 'icon-doujiang',
	无糖豆浆: 'icon-wutangdoujiang',
	红枣豆浆: 'icon-hongzaodoujiang',
	可乐: 'icon-kele',
	椰子水: 'icon-yezishui',
	珍珠奶茶: 'icon-zhenzhunaicha',
	蛋糕: 'icon-dangao',
	蛋挞: 'icon-danta',
	饼干: 'icon-binggan',
	巧克力豆饼干: 'icon-qiaokelidoubinggan',
	黑巧克力: 'icon-heiqiaokeli',
	'巧克力(黑)': 'icon-a-qiaokelihei',
	冰淇淋: 'icon-bingqilin',
	薯片: 'icon-shupian',
	薯条: 'icon-shutiao',
	炸土豆条: 'icon-zhatudoutiao',
	辣条: 'icon-latiao',
	炸鸡: 'icon-zhaji',
	海苔: 'icon-haitai',
	海带: 'icon-haidai',
	紫薯: 'icon-zishu',
	花生: 'icon-huasheng',
	花生米: 'icon-huashengmi',
	瓜子: 'icon-guazi',
	核桃肉: 'icon-hetaorou',
	夏威夷果: 'icon-xiaweiyiguo',
	杏仁: 'icon-xingren',
	牛油果: 'icon-niuyouguo',
	鳄梨: 'icon-niuyouguo',
	梨: 'icon-li',
	橙子: 'icon-chengzi',
	蓝莓: 'icon-lanmei',
	猕猴桃: 'icon-mihoutao',
	石榴: 'icon-shiliu',
	哈密瓜: 'icon-hamigua',
	火龙果: 'icon-huolongguo',
	芒果: 'icon-mangguo',
	葡萄: 'icon-putao',
	桑葚: 'icon-sangshen',
	西瓜: 'icon-xigua',
	草莓: 'icon-caomei',
	樱桃: 'icon-yingtao',
	柿子: 'icon-shizi',
	红枣: 'icon-hongzao',
	白糖: 'icon-baitang',
	黄油: 'icon-huangyou',
	橄榄油: 'icon-ganlanyou',
	芝麻酱: 'icon-zhimajiang',
	黑芝麻: 'icon-heizhima',
	黑芝麻糊粉: 'icon-heizhimahufen',
	面条: 'icon-miantiao',
	洋葱: 'icon-yangcong',
	豆奶: 'icon-dounai'
}

export function getIngredientImagePath(name, category = '') {
	const key = `${name || ''}`.trim()
	const file = NAME_TO_FILE[key] || CATEGORY_TO_FILE[`${category || ''}`.trim()]
	return file ? ingredientStaticUrl(file) : ''
}

export function getIngredientIconfontClass(name) {
	return NAME_TO_ICONFONT[`${name || ''}`.trim()] || ''
}

export function getIngredientSymbolId(name) {
	const cls = getIngredientIconfontClass(name)
	return cls ? `#${cls}` : ''
}

export function getCategoryEmoji(category) {
	return CATEGORY_TO_EMOJI[`${category || ''}`.trim()] || '🍽️'
}

