const INGREDIENT_STATIC_VERSION = 3

function ingredientStaticUrl(filename) {
	return `/static/ingredients/${filename}?v=${INGREDIENT_STATIC_VERSION}`
}

const NAME_TO_FILE = {
	苹果: 'apple.png',
	香蕉: 'banana.png',
	牛肉: 'beef.png',
	西兰花: 'broccoli.png',
	花椰菜: 'broccoli.png',
	胡萝卜: 'carrot.png',
	鸡胸肉: 'chicken_breast.png',
	鸡肉: 'chicken_breast.png',
	黄瓜: 'cucumber.png',
	鸡蛋: 'egg.png',
	生菜: 'lettuce.png',
	牛奶: 'milk.png',
	蘑菇: 'mushroom.png',
	香菇: 'mushroom.png',
	面条: 'noodle..png',
	洋葱: 'onion.png',
	橙子: 'orange.png',
	猪肉: 'pork.png',
	土豆: 'potato.png',
	马铃薯: 'potato.png',
	大米: 'rice.png',
	米饭: 'rice.png',
	虾: 'shrimp.png',
	豆腐: 'tofu.png',
	番茄: 'tomato.png',
	西红柿: 'tomato.png'
}

const CATEGORY_TO_FILE = {
	水果: 'apple.png',
	蔬菜: 'broccoli.png',
	肉类: 'beef.png',
	蛋奶: 'egg.png',
	海鲜: 'shrimp.png',
	饮料: 'milk.png',
	调味品: 'onion.png',
	其他: 'tomato.png'
}

const CATEGORY_TO_EMOJI = {
	水果: '🍎',
	蔬菜: '🥬',
	肉类: '🥩',
	蛋奶: '🥚',
	海鲜: '🦐',
	饮料: '🥛',
	调味品: '🧂',
	其他: '🍽️'
}

const NAME_TO_ICONFONT = {
	苹果: 'icon-pingguo',
	香蕉: 'icon-xiangjiao',
	牛肉: 'icon-niurou',
	西兰花: 'icon-xilanhua',
	熟西兰花: 'icon-shuxilanhua',
	菠菜: 'icon-bocai',
	生菜: 'icon-shengcai',
	卷心菜: 'icon-juanxincai',
	白菜: 'icon-baicai',
	小白菜: 'icon-xiaobaicai',
	菜心: 'icon-caixin',
	青菜: 'icon-qingcai',
	上海青: 'icon-shanghaiqing',
	娃娃菜: 'icon-wawacai',
	花菜: 'icon-huacai',
	南瓜: 'icon-nangua',
	贝贝南瓜: 'icon-beibeinangua',
	黄瓜: 'icon-huanggua',
	青椒: 'icon-qingjiao',
	冬瓜: 'icon-donggua',
	豆芽: 'icon-douya',
	豌豆: 'icon-wandou',
	毛豆: 'icon-maodou',
	黄豆: 'icon-huangdou',
	黑豆: 'icon-heidou',
	红豆: 'icon-hongdou',
	白萝卜: 'icon-bailuobu',
	胡萝卜: 'icon-huluobu',
	红萝卜: 'icon-huluobu',
	生胡萝卜: 'icon-shenghuluobu',
	萝卜: 'icon-luobu',
	番茄: 'icon-fanqie',
	西红柿: 'icon-fanqie',
	小番茄: 'icon-xiaofanqie',
	圣女果: 'icon-shengnvguo',
	茄子: 'icon-qiezi',
	紫茄子: 'icon-qiezi',
	长茄子: 'icon-qiezi',
	土豆: 'icon-tudou',
	马铃薯: 'icon-tudou',
	山药: 'icon-shanyao',
	玉米: 'icon-xianyumi',
	鲜玉米: 'icon-xianyumi',
	黄玉米: 'icon-huangyumi',
	白玉米: 'icon-baiyumi',
	大米: 'icon-mifan',
	米饭: 'icon-mifan',
	鸡蛋: 'icon-jidan',
	鸡蛋白: 'icon-jidanbai',
	卤蛋: 'icon-ludan',
	煎蛋: 'icon-jiandan',
	煮鸡蛋: 'icon-zhujidan',
	茶叶蛋: 'icon-chayedan',
	牛奶: 'icon-niunai',
	全脂牛奶: 'icon-quanzhiniunai',
	脱脂牛奶: 'icon-tuozhiniunai',
	伊利纯牛奶: 'icon-yilichunniunai',
	酸奶: 'icon-suannai',
	无糖酸奶: 'icon-wutangsuannai',
	奶酪: 'icon-nailao',
	豆腐: 'icon-doufu',
	内脂豆腐: 'icon-neizhidoufu',
	内酯豆腐: 'icon-neizhidoufu',
	油豆腐: 'icon-youdoufu',
	豆皮: 'icon-doupi',
	腐竹: 'icon-fuzhu',
	千张: 'icon-qianzhang',
	蘑菇: 'icon-mogu',
	香菇: 'icon-mogu',
	金针菇: 'icon-jinzhengu',
	牛排: 'icon-niupai',
	猪肉: 'icon-zhurou',
	'猪肉(肥瘦)': 'icon-a-zhuroufeisou',
	鸡肉: 'icon-jirou',
	鸡胸肉: 'icon-jixiongrou',
	烤鸡翅: 'icon-kaojichi',
	排骨: 'icon-paigu',
	培根: 'icon-peigen',
	火腿: 'icon-huotui',
	火腿肠: 'icon-huotuichang',
	香肠: 'icon-xiangchang',
	炸鸡腿: 'icon-zhajitui',
	虾: 'icon-xia',
	虾仁: 'icon-xiaren',
	鸡尾虾: 'icon-jiweixia',
	生三文鱼: 'icon-shengsanwenyu',
	'鲑鱼(三文鱼)': 'icon-a-guiyusanwenyu',
	鲑鱼: 'icon-a-guiyusanwenyu',
	三文鱼: 'icon-a-guiyusanwenyu',
	面条: 'icon-miantiao',
	煮面条: 'icon-zhumiantiao',
	方便面: 'icon-fangbianmian',
	包子: 'icon-shengxian-shushi',
	馒头: 'icon-shengxian-shushi',
	花卷: 'icon-huajuan',
	吐司: 'icon-tusi',
	全麦面包: 'icon-quanmaimianbao',
	豆浆: 'icon-doujiang',
	无糖豆浆: 'icon-wutangdoujiang',
	红枣豆浆: 'icon-hongzaodoujiang',
	大葱: 'icon-dacong',
	生姜: 'icon-shengjiang',
	杏: 'icon-xing',
	猕猴果: 'icon-mileguo',
	可乐: 'icon-kele',
	椰子水: 'icon-yezishui',
	珍珠奶茶: 'icon-zhenzhunaicha',
	蛋糕: 'icon-dangao',
	蛋挞: 'icon-danta',
	饼干: 'icon-binggan',
	巧克力豆饼干: 'icon-qiaokelidoubinggan',
	黑巧克力: 'icon-heiqiaokeli',
	'巧克力(黑)': 'icon-a-qiaokelihei',
	冰淇淋: 'icon-bingqilin',
	薯片: 'icon-shupian',
	薯条: 'icon-shutiao',
	炸土豆条: 'icon-zhatudoutiao',
	辣条: 'icon-latiao',
	炸鸡: 'icon-zhaji',
	海苔: 'icon-haitai',
	海带: 'icon-haidai',
	紫薯: 'icon-zishu',
	花生: 'icon-huasheng',
	花生米: 'icon-huashengmi',
	瓜子: 'icon-guazi',
	核桃肉: 'icon-hetaorou',
	夏威夷果: 'icon-xiaweiyiguo',
	杏仁: 'icon-xingren',
	牛油果: 'icon-niuyouguo',
	鳄梨: 'icon-niuyouguo',
	梨: 'icon-li',
	橙子: 'icon-chengzi',
	蓝莓: 'icon-lanmei',
	猕猴桃: 'icon-mihoutao',
	石榴: 'icon-shiliu',
	哈密瓜: 'icon-hamigua',
	火龙果: 'icon-huolongguo',
	芒果: 'icon-mangguo',
	葡萄: 'icon-putao',
	桑葚: 'icon-sangshen',
	西瓜: 'icon-xigua',
	草莓: 'icon-caomei',
	樱桃: 'icon-yingtao',
	柿子: 'icon-shizi',
	山竹: 'icon-shanzhu',
	杨桃: 'icon-yangtao',
	车厘子: 'icon-chelizi',
	椰子: 'icon-yezi',
	莲雾: 'icon-lianwu',
	柚子: 'icon-youzi',
	木瓜: 'icon-mugua',
	柠檬: 'icon-ningmeng',
	荔枝: 'icon-lizhi',
	榴莲: 'icon-liulian',
	红枣: 'icon-hongzao',
	白糖: 'icon-baitang',
	黄油: 'icon-huangyou',
	橄榄油: 'icon-ganlanyou',
	芝麻酱: 'icon-zhimajiang',
	黑芝麻: 'icon-heizhima',
	黑芝麻糊粉: 'icon-heizhimahufen',
	糖: 'icon-baitang',
	白砂糖: 'icon-baitang',
	香油: 'icon-ganlanyou',
	油: 'icon-ganlanyou',
	辣椒油: 'icon-honglajiao',
	面条: 'icon-miantiao',
	洋葱: 'icon-yangcong',
	豆奶: 'icon-dounai'
}

const KEYWORD_TO_ICONFONT = [
	{ keyword: '茄子', icon: 'icon-qiezi' },
	{ keyword: '西红柿', icon: 'icon-fanqie' },
	{ keyword: '番茄', icon: 'icon-fanqie' },
	{ keyword: '牛肉', icon: 'icon-niurou' },
	{ keyword: '鸡蛋', icon: 'icon-jidan' },
	{ keyword: '土豆', icon: 'icon-tudou' },
	{ keyword: '马铃薯', icon: 'icon-tudou' },
	{ keyword: '黄瓜', icon: 'icon-huanggua' },
	{ keyword: '洋葱', icon: 'icon-yangcong' },
	{ keyword: '胡萝卜', icon: 'icon-huluobu' },
	{ keyword: '萝卜', icon: 'icon-luobu' },
	{ keyword: '虾', icon: 'icon-xia' },
	{ keyword: '鸡胸', icon: 'icon-jixiongrou' },
	{ keyword: '鸡肉', icon: 'icon-jirou' },
	{ keyword: '猪肉', icon: 'icon-zhurou' },
	{ keyword: '豆腐', icon: 'icon-doufu' },
	{ keyword: '蘑菇', icon: 'icon-mogu' },
	{ keyword: '香菇', icon: 'icon-mogu' },
	{ keyword: '西兰花', icon: 'icon-xilanhua' },
	{ keyword: '生菜', icon: 'icon-shengcai' },
	{ keyword: '菠菜', icon: 'icon-bocai' },
	{ keyword: '白菜', icon: 'icon-baicai' },
	{ keyword: '青菜', icon: 'icon-qingcai' },
	{ keyword: '香蕉', icon: 'icon-xiangjiao' },
	{ keyword: '苹果', icon: 'icon-pingguo' },
	{ keyword: '橙子', icon: 'icon-chengzi' }
	,
	{ keyword: '胡椒', icon: 'icon-Pepper' },
	{ keyword: 'pepper', icon: 'icon-Pepper' },
	{ keyword: '盐', icon: 'icon-Salt' },
	{ keyword: 'salt', icon: 'icon-Salt' },
	{ keyword: '酱油', icon: 'icon-Soya' },
	{ keyword: '生抽', icon: 'icon-Soya' },
	{ keyword: '老抽', icon: 'icon-Soya' },
	{ keyword: 'soya', icon: 'icon-Soya' },
	{ keyword: '醋', icon: 'icon-Vinegar' },
	{ keyword: '米醋', icon: 'icon-Vinegar' },
	{ keyword: '陈醋', icon: 'icon-Vinegar' },
	{ keyword: 'vinegar', icon: 'icon-Vinegar' },
	{ keyword: '蜂蜜', icon: 'icon-Honey' },
	{ keyword: 'honey', icon: 'icon-Honey' },
	{ keyword: '番茄酱', icon: 'icon-Ketchup' },
	{ keyword: 'ketchup', icon: 'icon-Ketchup' },
	{ keyword: '橄榄油', icon: 'icon-ganlanyou' },
	{ keyword: 'olive oil', icon: 'icon-ganlanyou' },
	{ keyword: 'oliveoil', icon: 'icon-ganlanyou' },
	{ keyword: '白糖', icon: 'icon-baitang' },
	{ keyword: '砂糖', icon: 'icon-baitang' },
	{ keyword: 'sugar', icon: 'icon-baitang' },
	{ keyword: '糖', icon: 'icon-baitang' },
	{ keyword: '辣椒油', icon: 'icon-honglajiao' },
	{ keyword: '香油', icon: 'icon-ganlanyou' },
	{ keyword: '食用油', icon: 'icon-ganlanyou' },
	{ keyword: '油', icon: 'icon-ganlanyou' },
	{ keyword: '西葫芦', icon: 'icon-xihulu' },
	{ keyword: '秋葵', icon: 'icon-qiukui' },
	{ keyword: '红辣椒', icon: 'icon-honglajiao' },
	{ keyword: '紫甘蓝', icon: 'icon-ziganlan' },
	{ keyword: '大蒜', icon: 'icon-dasuan' },
	{ keyword: '蒜末', icon: 'icon-dasuan' },
	{ keyword: '蒜蓉', icon: 'icon-dasuan' },
	{ keyword: '八角', icon: 'icon-bajiao' },
	{ keyword: '竹笋', icon: 'icon-zhusun' },
	{ keyword: '春笋', icon: 'icon-zhusun' },
	{ keyword: '藕', icon: 'icon-ou' },
	{ keyword: '莲藕', icon: 'icon-ou' },
	{ keyword: '红薯', icon: 'icon-hongshu1' },
	{ keyword: '地瓜', icon: 'icon-hongshu1' },
	{ keyword: '玉米粒', icon: 'icon-xianyumi' },
	{ keyword: '大葱', icon: 'icon-dacong' },
	{ keyword: '生姜', icon: 'icon-shengjiang' },
	{ keyword: '姜', icon: 'icon-shengjiang' },
	{ keyword: '杏', icon: 'icon-xing' },
	{ keyword: '猕猴果', icon: 'icon-mileguo' }
	,
	{ keyword: '山竹', icon: 'icon-shanzhu' },
	{ keyword: '杨桃', icon: 'icon-yangtao' },
	{ keyword: '车厘子', icon: 'icon-chelizi' },
	{ keyword: '樱桃', icon: 'icon-chelizi' },
	{ keyword: '椰子', icon: 'icon-yezi' },
	{ keyword: '莲雾', icon: 'icon-lianwu' },
	{ keyword: '柚子', icon: 'icon-youzi' },
	{ keyword: '西瓜', icon: 'icon-xigua' },
	{ keyword: '柿子', icon: 'icon-shizi' },
	{ keyword: '木瓜', icon: 'icon-mugua' },
	{ keyword: '柠檬', icon: 'icon-ningmeng' },
	{ keyword: '青柠', icon: 'icon-ningmeng' },
	{ keyword: 'lemon', icon: 'icon-ningmeng' },
	{ keyword: '荔枝', icon: 'icon-lizhi' },
	{ keyword: '榴莲', icon: 'icon-liulian' },
	{ keyword: 'durian', icon: 'icon-liulian' },
	{ keyword: '包子', icon: 'icon-shengxian-shushi' },
	{ keyword: '馒头', icon: 'icon-shengxian-shushi' }
]

export function getIngredientImagePath(name, category = '') {
	const key = `${name || ''}`.trim()
	const file = NAME_TO_FILE[key] || CATEGORY_TO_FILE[`${category || ''}`.trim()]
	return file ? ingredientStaticUrl(file) : ''
}

export function getIngredientIconfontClass(name) {
	const text = `${name || ''}`.trim()
	if (!text) return ''
	const exact = NAME_TO_ICONFONT[text]
	if (exact) return exact
	const lower = text.toLowerCase()
	const hit = KEYWORD_TO_ICONFONT.find((x) => lower.includes(`${x.keyword}`.toLowerCase()))
	return hit ? hit.icon : ''
}

function getCategoryFallbackIconfontClass(category) {
	const cat = `${category || ''}`.trim()
	if (cat === '水果') return 'icon-shuiguolanzi'
	if (cat === '蔬菜') return 'icon-huacai1'
	if (cat === '海鲜') return 'icon-shengxian-haixian1'
	if (cat === '肉类') return 'icon-shengxian-roulei'
	if (cat === '饮料') return 'icon-yinliao'
	if (cat === '调味品') return 'icon-tiaoliao'
	if (cat === '其他') return 'icon-bianzu'
	return ''
}

export function getIngredientSymbolId(name, category = '') {
	const cls = getIngredientIconfontClass(name) || getCategoryFallbackIconfontClass(category)
	return cls ? `#${cls}` : ''
}

export function getCategoryEmoji(category) {
	return CATEGORY_TO_EMOJI[`${category || ''}`.trim()] || '🍽️'
}

